CREATE TABLE `wp_users` (  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `user_login` varchar(60) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `user_pass` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `user_nicename` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `user_email` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `user_url` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `user_registered` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',  `user_activation_key` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `user_status` int(11) NOT NULL DEFAULT '0',  `display_name` varchar(250) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  PRIMARY KEY (`ID`),  KEY `user_login_key` (`user_login`),  KEY `user_nicename` (`user_nicename`),  KEY `user_email` (`user_email`)) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_users` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_users` VALUES('1', 'wpengine', '$P$BARwjh18t6MBy/O1x3BLaBLwx.zbRw0', 'wpengine', 'bitbucket@wpengine.com', 'http://wpengine.com', '2017-11-16 14:47:09', '', '0', 'wpengine');
INSERT INTO `wp_users` VALUES('2', 'casterarticles', '$P$B.SMi05.emu7C7bMHnjf8MoFqfzr0//', 'casterarticles', 'dfelker@agilevent.com', 'http://casterarticles.wpengine.com', '2018-04-10 09:28:20', '', '0', 'casterarticles');
INSERT INTO `wp_users` VALUES('3', 'donnfelker', '$P$BYMDwd1ceUlQYFoOW6r2GzbMPQILgk.', 'donnfelker', 'donn@caster.io', 'https://www.donnfelker.com', '2018-04-10 16:18:50', '1523377130:$P$BhmMBJD2dC5M9Z5KbGgjqzeB/nLvFv.', '0', 'Donn Felker');
INSERT INTO `wp_users` VALUES('4', 'craigrussell', '$P$BLYFgEgP/q/j8SyCRAaJZl2B1deGH..', 'craigrussell', 'craig.russell.1986@gmail.com', '', '2018-04-10 16:40:44', '', '0', 'Craig Russell');
/*!40000 ALTER TABLE `wp_users` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
